language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: D90Gaefivt6HGOy0/mqSigCe93Ic4rCBdB3ymHyxj2NDy88jU9x/+QGtS6Ze/cTY+C99hBY4EG8sWGLHZtKvHqaE/4I1V7gltAQ+/2oDCCLtHxsgqF2jyiSbFKaPifVFZFxWjV8vFq7W1BNYWuoUXlbyLDd4JVeaXhZDct25bak9ErGcXdyNdxN1PvnKQBWJ8as2QpcaviborfMZDF3a7zVJGObPKGVJskq+ON7bqZ02zSHBl7xlYxC0mbJEE6DYfhuxDLTUjpCGfVKySTfHC2YKa3KufeR/fgXDIqdFHdjkDiBTuFTu1cy16zk6f+9gsFkqBVJztZtUpelKTXv9ufcg94C1Bic61W7372+O1fJSO6EYCzNKRIu2GYAYDC1PPjjwE1JCYHpdAzdtf4+i/W74IPXDwOGw4RmIxNJBj16Hn26GMG9mgVJWa9sJeIYihfr2zW8X3ZZic77vAN7FFmAY+gphl0uRJeGWc7tP6yOSxtAML5hG9N7t7MdIE7dw5qVcO0/tK/uibWiVDxASCuwoqq8ERO9OIsJPlOafTHyc7bQnaOIMaIrI6gy/R8G66kZwusWHFHJNyffRhYH3pAJ1oQQtb0O35IAC7BAs29MA+er20BJrx4UpmFliRo+rF2mZo6cMs/5KPBF7jqym9/XxDzy9Jo1GfEGcQVMfS2o=
  app: mighty-falls-28563
  on:
    repo: spoofBlue/Server-Capstone
