language: node_js
node_js:
- 8.11.4
services:
- mongodb
deploy:
  provider: heroku
  app: mighty-falls-28563
  api_key:
    secure: KJFyQQhLVeFsE8jiN+ittudoj+ecCVH7f1f1fjRRrFeyAf2CrJLA6oB/w/DA4GOqckBwoEl/bvaNmG5/4cZNqt0Hc9eETQr+D4EIMtjQ9PGt8aZDKfwYooTboR9gShcskjF/yyyKAieHjXnw4nkg7PYzoOju3UeWL4DkdS00Z427kscQIZfVaE3BZ5UTmZFmSgsBjG0g/nuKl3D/O734YuMEBubcBryi/e+Bs365cxc69NErgbdDWlsHBMCW1kuhHpbg8MoSonASe1uv8Hzg7whK1u/jLfo9b78TPkp7yHtn4MieKETLcsRsB9/2xVCtqcu8bCQji4wEGMGGLxH0ium86kPpNhWlHI7n0lt/ywIBnC1Re9FUgF89UMqleWbYFK9ndmfFbmlDx9TWA5nd5S/Ax3AzfUb+YDph/ycYFuWbF+zJC0QZfPZnH4DMGc9O+9sAPLKm8wT+Yl8gOcG8gPPfj89tCp/FMqJ/T5ULlfeb3ASFwYPBpWTtHoH3WmOrGSqqm70Ydl6rXDAojvdSAJSsnB8wunwTiKtTk30SJNeb6xmMc9Q3XvrtBWbFy6gulgkTCnFHOxSfRBi8TovZGGlBl4lu27G0uHZCTgGgPVhP4QzYMuBBvv9+AnnAiziFq+hbJQGAWyva7ogE/OSLesoYvW0LjEdddKnjKZTUfmQ=
