language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: VZF1tTf9cUnVASaqA5K6KO+/E5IStsZFJuwUd6aCvFmCk7yHaDziXA3NAHsHbYTJfPXHgMb/BMwU5rs0Neq2icj36/U036RO4Resws7BEu39NEJy5zuCmaZ/1xkwU5VixCLms5yrcWblFYOa5glKRXMKhZR9svLsVa2OMyXuOc38ZEXoZgYrSiqiMmF7nseO9Y4qVxo0JsgDFmf/mcknDHojRKhh43gcu6pusPPh57tI6G4Pj6KzU26k53X5moZPkGeoa5vZucht4meFf+yJR+xLiJw53UGAMYiykvLBbqBIRqzZl/as7xyvFds5lw4uUkadVbJb23feal6aioWF1BRWP2xXJg0ntyrfm+Ciw+mYI1/Jgyt7QVicQQNqpmS6BVrOtL/f5JE0NSnso26s2yiA0DXbUcw4Zmxa90NwsPkNod7zz7gtU0MBvdnhZj/i9lgQP+jiOfcAxLe+6QV4UOLqwBT2iP+jf9JhMiov5rgCIFFOYi8LNHNt+lp6Ab7Vzy4xrZIue0zKo3mdRaZRtpP5VqmmDYQIIyGwAfIB/ew9mfK9NXm//Vtg30pHX5iDmRWMpITXTReR9M6KPyqamMqqcJW62nTPYbnFGGA2lUwlqJkZXk/TmnSNw6lwWK3wI+vZAuqfJ8QGdQ3A7OlPFA0HEyQfkPx3puRFQnnnjr8=
