language: node_js
node_js:
- 8.11.4
services:
- mongodb
deploy:
  provider: heroku
  app: mighty-falls-28563
  api_key:
    secure: jkx4MUEZTt2uO6IJCkxr3dVGZK61tbBefGz2D0VINk+BevPMrE/+e/jZ9qXGoh69oEgr6sQAw0tGYWtZ4LE/gnnxzxw8sDHGAS5bMDCq5eO/JsNA4ecwBPlt4eKPJWz/Tljxm0vo8Fkjh73RTtdIBhQY2vpVW2URNKn2fYJFG8TjT4teSgAVPFkvvdKw+E8YjhMDQF9yHcePwUVkHI6XNHJGsuCTEI1gvzXaQLoSSQhXMPcb8g7zkPwlr0CrCzA0k9VfDQH0h43ZxF/c3Nilf5lSMaLNFwkxxU4Gl9A0JB6HGVvJ8fxXxcLcNSdguTGlijYPZm+8pML+5hhTSKgxURVs+DVyubEfbKRlDOD9WFHEo/LG7kR5J+iIckQ+JMNrTTlUoI581Li5m9U+CKoKs1CHsfpWqCXIHogGEZbJaQnC5IrH/eVEjxpskaIYQqdbRqY/JW/cAGWBmSy7OYZyaJEaRSPMTMZQE/weXiChLKmL+SBtZLjN0DDqtKQaZJe6dlNm4k2ljKXZu9Gvu+C7gLmE62RLN1zl+cLClfmhU3QdOyzH3JsYnWOkFXraw1EOxh4RXfRC0lotlTzutMhl5qeRDtm9zV7SBNyZbpVb9uKAmUS7pr2WN+ZQ7N38VWq0maVdC9ByNbRfRrelObBFIeim0qMOzcTsstMLRylYwcY=
