language: node_js
node_js:
- 8.11.4
services:
- mongodb
deploy:
  provider: heroku
  app: mighty-falls-28563
  api_key:
    secure: pvuaMtFPA5Jo3xHSHzg6w1Kv6geGcidWJM1F4WTNi12dSThOBhyH05fwulr2wxMIPUPdttLTn5OkiW6Nja6rlInHsqbZHA7yyjXoKGcwBmtIKzD403ly9qA/eqQWTXt3w1IHh0aZo3p0Yz+TKOfgKCGcqDfgcovJMU/K3HicFpcusZz6xw6CgalRAfJmJ9oRwSZm4Amxq7N4sRxOkw23qpgHGG3wdkQewIsIEbw0Ky5UrwiYsENd1ctuaTPndQm96IhjWt5bIazv7zgo3gqktXgTkrXmOCPg00LqTSDG2R9RwqdeynUX5tkdizsKSG/KZd+UJaUH6kGdKVA+vI9Z3VDi+pFWzmvdmcaP2GAtrMU/9KyWng8X1hEAScrB+Koe5vig6Jvd2OOHc2boWDuMNIyK1aeVIPu1g7atxLlhhCGkhLXYTpywi68pNVEcPS7QM10MmABLKIQbOlLKhvh0910x8I4JHqRXx9xSyWbGYxCgwOPnrotn6NqVk5ahmWNd07/CcewoTrk/ySgHKb5Z0s0nS3siFUXZetkoFKPBF5NTfZrtHLl3PNNCgac6KHjfgN5mXqdEeWSXUfUUCsDnsaO9gdCEm8eQ0f89SSUDwS/b21Nxad+1lba+7msUxgK/c4bwHQomxH6inrCDIHZAETCsdXdpST9bKD4fDMRkDUI=
